### ISSUE TITLE
Consider Splitting Spack Repos

### ISSUE THREAD

**Issue by ChristianTackeGSI** [FairRootGroup/FairSoft#280]
@kresan, @dennisklein, and I highly consider untangling the FairSoft/spack builds for virgo/VAE, and for our main FairSoft users. We had some discussions and I am posting this issue (could be considered a Feature Request) to better track the current status.

### Spack Repo structure

We ccurrently have one spack package repo with a mixture of
1. "our own business": FairRoot-and-friends. Basically, what could resemble FairSoft-legacy (at least how I see it)
2. "locally forked": We have copied over something from upstream, but haven't yet contributed it back. But really, we should!
3. "backported": We just copied the recipe from upstream. Because we needed a newer one.
4. special use cases (none as of now, see below)

(2) and (3) are quite alike. One could argue that they're really the same.

### multiple spack repos

What about splitting this really into distinct repos? We can just put them in different directories and be done.
We could have:
* `repos/fairsoft/`, `fairsoft-core/`, or `fairsoft-common/` to handle (1) and use `spack_version` as needed (see #279).
* `repos/fairsoft-forked/` handles (2). If we track spack/develop as one of our working versions, than we should aim at this always being empty!
* `repos/fairsoft-backported/` handles (3) for the main spack version, that we give to our main users.
* `repos/vae-backported/` handles (3) for VAE
* `repos/vae-forked/` handles (2) for VAE, if VAE actually needs that. It might need it, if it can't use `fairsoft-forked/`, or doesn't want to wait for the backport.
* `disabled-builtin-helpers/`: All the recipes that Dennis needs for his disabled-builtin idea. Most likely the checkers with `provides()` and maybe some BundlePackages with the same name a a builtin package name to fullfill the dependencies of (1)

And users then can just mix and match by doing `spack repo add repos/vae-backported`. That's maybe not totally nice, but we already have a setup list that let's people setup spack in various ways. A few repos wont hurt.
@dennisklein also proposed a `thisfairsoft.sh` script for the setup. That should handle the major use case for our main users. VAE can be consider "internal" and will know what to do.

### spack versions

The `spack` submodule would track our officially supported spack version. That would still be the version that the CI runs stuff. So `fairsoft-backported` will likely always have some entries, but hopefully not too many. When they grow too much, we know, that we need to upgrade the official version.

Adventurous developers run spack/develop with only `faisoft-common/` and `fairsoft-forked/` emabled.

And VAE runs their own spack version, with `faisoft-common/`, `faisoft-forked/` and `vae-backported/` enabled.

If needed, we could track the VAE-spack in a `vae/spack/` submodule.

### Remaining issues

We might end up with three `config/` as well. I haven't thought that through fully.

**Comment by ChristianTackeGSI** [comment]
I would propose we start with the following two tasks:
- [ ] #279 to make our recipes at least ready to work with spack 0.13.x and 0.14.x at the same time
- [ ] Dennis' `thisfairsoft.sh` idea to better transition our users into the multi-repo world.

Both are good to have even without any untangling, or multi-repo moving anyway.

**Comment by ChristianTackeGSI** [comment]
* [ ] #280 will get us the `thisfairsoft.sh` script and starts to move the main repo over to `repos/fairsoft`

Next points:
* I called the main repo `repos/fairsoft/`. Do we want any suffixes like `-main`, or `-common` to be clear, that this is the repo, that everybody will likely want?
* In the first post in this issue, I suggested a bunch of new repo names like `repos/fairsoft-forked/`, or `repos/vae-backported/`. We should agree on which we want to start with?
* Do we want "forked" and "backported" to be in different repos? Or should we put both in the same as in "tight cooperation with upstream, either forked, but going to submit patches soon or just backported"?

**Comment by dennisklein** [comment]
> * I called the main repo repos/fairsoft/. Do we want any suffixes like -main, or -common to be clear, that this is the repo, that everybody will likely want?

I prefer the main repo without any suffix.

> * In the first post in this issue, I suggested a bunch of new repo names like repos/fairsoft-forked/, or repos/vae-backported/. We should agree on which we want to start with?
> * Do we want "forked" and "backported" to be in different repos? Or should we put both in the same as in "tight cooperation with upstream, either forked, but going to submit patches soon or just backported"?

Let's start with a single additional `fairsoft-backported` or `fairsoft-backports` repo. We can put the forks there, too. Let's see how this plays out and possibly split further in the future, if we feel it is necessary.

**Comment by ChristianTackeGSI** [comment]
- [X] #281 done
- [ ] #284 brings the big VAE split _and_ upgrades spack to 0.14.x

Let's see, how this works…

**Comment by dennisklein** [comment]
There is certainly still some cleanup work to do in the now split-up repos, but I am closing this discussion as it served its purpose as preparation for the split which is now successfully implemented.
